[supabase]
url = "https://muudoenycgafzmkryacn.supabase.co"
api_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11dWRvZW55Y2dhZnpta3J5YWNuIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NDMyNTI4NywiZXhwIjoyMDU5OTAxMjg3fQ.p9ly6if55dzjPrBJci6_bFJw25Nd1Gvj0PTK3rvCx6g"