[auth]
redirect_uri="http://localhost:8501/oauth2callback"
cookie_secret="d4f7e6a9b8c3e2f1a0d9c8b7a6e5f4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f7"

[auth.google]
client_id="669584633876-rs7m8431rrkl29fovfolcknsvu7d2565.apps.googleusercontent.com"
client_secret="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"
server_metadata_url="https://accounts.google.com/.well-known/openid-configuration"